// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP_zXTU7tjaKqGkjSnQkKBcSUcj8BkhnQ',
    appId: '1:824079717751:web:f06b76e2edefead5d5bd72',
    messagingSenderId: '824079717751',
    projectId: 'jarvis-9a55e',
    authDomain: 'jarvis-9a55e.firebaseapp.com',
    storageBucket: 'jarvis-9a55e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzIZeS3CIWEvmg3AvxPypTW0vAHBUdQoY',
    appId: '1:824079717751:android:4f3cc709dc85bd55d5bd72',
    messagingSenderId: '824079717751',
    projectId: 'jarvis-9a55e',
    storageBucket: 'jarvis-9a55e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANGxytec-l4EOy-3DBSIsZ17ueoGBlezg',
    appId: '1:824079717751:ios:358122550bf9d016d5bd72',
    messagingSenderId: '824079717751',
    projectId: 'jarvis-9a55e',
    storageBucket: 'jarvis-9a55e.firebasestorage.app',
    iosBundleId: 'com.vm.flutterTopics',
  );
}
